# Generated by Django 2.1.5 on 2019-05-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercall',
            name='status',
            field=models.IntegerField(choices=[(0, 'Обрабатывается'), (1, 'Принято'), (2, 'Отменено')], default=0),
        ),
    ]
