# Generated by Django 2.1.5 on 2019-05-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20190523_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=15)),
                ('delivery_type', models.IntegerField(choices=[(0, 'Самовывоз'), (1, 'Курьер')], default=0)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='ordercall',
            old_name='ordered_time',
            new_name='call_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Обрабатывается'), (1, 'Принято'), (2, 'Отменено'), (3, 'Завершено')], default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_detail',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.OrderDetail'),
            preserve_default=False,
        ),
    ]
