# Generated by Django 2.1.5 on 2019-05-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20190523_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='customer_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='customer_phone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='last_name',
            field=models.CharField(default='LastName', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
